<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <StartupObject>PersistenceExample</StartupObject>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Orchestration/Orchestration.csproj" />
    <ProjectReference Include="../Shared/Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="PersistenceExample.cs" />
  </ItemGroup>
</Project>

